services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: {{DB_USER}}
      POSTGRES_PASSWORD: {{DB_PASSWORD}}
      POSTGRES_DB: {{DB_NAME}}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  bot:
    build:
      context: .
      dockerfile: bot.dockerfile
    depends_on:
      - db
    env_file:
    - .env

  webhook:
    build:
      context: .
      dockerfile: webhook.dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
    - .env
volumes:
  db_data: